# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)

# Packages needed to generate model predictions
if (FALSE) {
    library(parsnip)
    library(rpart)
    library(workflows)
}
b <- board_folder(path = "pins-r")
v <- vetiver_pin_read(b, "cars_mpg", version = "20221121T142337Z-d18ec")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
