name: Verify minimal model performance

on:
  # run it on push to the default repository branch
  push:
    branches: [main]
  # run it during pull request
  pull_request:
  
jobs:
  verify:
    runs-on: rocker/r-ver:4.2.0
    env:
      RENV_CONFIG_REPOS_OVERRIDE:  "https://packagemanager.rstudio.com/cran/latest"
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true
    - uses: r-lib/actions/setup-renv@v2
    - name: run verification
      run: Rscript verify.R
      
  